# Generated by Django 4.2.5 on 2023-09-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.SmallIntegerField(),
        ),
    ]
