# Generated by Django 4.2.5 on 2023-09-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'time')},
        ),
    ]
