# Generated by Django 4.2.5 on 2023-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_category_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.CharField(default='S1', max_length=5),
            preserve_default=False,
        ),
    ]
