# Generated by Django 4.2.5 on 2023-09-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_booking_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'time', 'table')},
        ),
    ]
