import React, { useState } from "react";
import Table from "./Table";

const TablePlan = ({ normalCol, hoverCol, inActiveCol, tableList,tableSelected={tableSelected},setTableSelected={setTableSelected} }) => {
  
  return (
    <>
      {/* <p>{tableSelected}</p> */}
      <Table
        className="table-reserve-l"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"L1"}
        tableSelected={tableSelected}
        setTableSelected={setTableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-m"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"M1"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S1"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S2"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S3"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-m"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"M2"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S4"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S5"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <div className="table-reserve-space"></div>

      <Table
        className="table-reserve-m"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"M3"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S6"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S7"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-l"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"L2"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S8"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S9"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-m"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"M4"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
      <Table
        className="table-reserve-s"
        normalCol={normalCol}
        hoverCol={hoverCol}
        inActiveCol={inActiveCol}
        id={"S10"}
        setTableSelected={setTableSelected}
        tableSelected={tableSelected}
        tableList={tableList}
      ></Table>
    </>
  );
};

export default TablePlan;
